[build]
  base    = "frontend"
  publish = "frontend/build"
  command = "CI= npm run build"

[build.environment]
  NODE_VERSION = "18.20.4"
  REACT_APP_API_URL = "https://informa-tics-production.up.railway.app"
