[build]
  command = "CI= npm run build"   # <- esto hace que los warnings NO rompan
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.4"
  REACT_APP_API_BASE = "https://informa-tics-production.up.railway.app"
  REACT_APP_API_URL  = "https://informa-tics-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
